export const en = {
    //Login Page
    loginMessage: 'Login to the Storytellers App',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign In',
    registerMessage: 'Register a New Account',
    forgotPassword: 'Forgot Password',
    dontWantAccount: "Don't want an account?",
    loginAsGuest: 'Login as a Guest',
    invalidLogin: "Invalid Login Information",
    makeSureUserValid:  "Please make sure the username and password you enter is valid.",
    missingLogin: "Missing Login Information",
    makeSureInfoEntered: "Please make sure you have entered information in all fields before trying to login.",
    
    //Registration Page
    createYourAccountMessage: 'Create Your Storytellers Account',
    fullName: "Full Name",
    email: 'Email',
    confirmPassword: "Confirm Password",
    register: "Register",
    alreadyHaveAccount: 'Already have an account?',
    login: 'Login',
    termsOfServiceMessage: 'By selecting Register, you agree to the',
    termsOfService: "Terms of Service",
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    missingRegistrationInfo:  "Missing Registration Information",
    makeSureRegisterInfoEntered: "Please make sure you have entered information in all fields before trying to register.",
    passwordMismatch: "Please make sure that your new password is the same for both fields.",
    invalidEmail: "Invalid Email",
    makeSureValidEmailEntered:  "Please make sure you have entered a valid email before trying to register.",
    invalidRegistration: "Invalid Registration Information",

    //Email Verification
    incorrectEmailCode: "Incorrect code, please try again",
    errorReachingServer: "There was a problem reaching the server. Please try again",
    codeSentToEmail: 'A code was sent to your email',
    pleaseEnterCodeHere: 'Please enter it here to verify your email',
    verificationCode: "Verification Code",
    confirm: 'Confirm',
    resendCode: "Resend verification code",

    //HomeScreen
    search: 'Search',
    helpCapitals: 'HELP',
    helpHomeTitle: 'This is the Home Screen',
    helpHomeStories: "All of the stories made by users will appear here. You can scroll through them, or click on any story to view its comments.",
    helpHomeLikes: "If you want to \"like\" a story, tap the heart. If you want to comment on a story, tap the speech bubble.",
    helpHomeRecording: 'Tap the blue microphone button to record your own story!',

    //CardFooter
    pleaseLoginToLike: "Please login to like a story",
    pleaseLoginToRecord: "Please login to record a story",
    reply: "Reply",
    comment: 'Comment',
    audio: 'Audio',
    deleteConfirmation: 'Are you sure that you want to delete this story?',
    cancel: 'Cancel',
    yes: 'Yes',
    flagSentForReview: 'This post has been sent to the admins for review',

    //ResponseScreen
    responses: 'Responses',

    //StorySaveScreen
    helpStorySaveTitle: "This is the StorySave Collection Screen",
    helpStorySaveStories: "All of the stories here are from the SC-Radio-CC StorySave collection. You can scroll through them, or click on any story to view its comments.",
    storySaveCollection: "StorySave Collection",

    //RadioPlayer
    helpRadioTitle: 'This is the SC-Radio-CC Screen',
    helpRadioMessage: 'Here you can listen to the SC-Radio-CC station, streaming live!',
    scRadio: 'SC-Radio-CC',

    //AdminPanel
    helpAdminTitle: 'This is the Admin Panel',
    helpAdminStories: 'Here you can approve or reject stories that are awaiting approval.',
    helpAdminControls: 'Tap the green thumbs up to approve a story, or tap the red thumbs down to reject a story.',
    adminPanel: 'Admin Panel',

    //DrawerContent
    pleaseLoginToViewProfile: "Please login to view profile information",
    guestUser: 'Guest User',
    home: 'Home',
    profile: 'Profile',
    privacy: 'Privacy',
    signOut: 'Sign Out',

    //ProfileScreen
    nameChangeSuccess: "Name Change Successful",
    nameUpdateFail: "Name Update Failed.",
    pleaseTryAgain: "Please Try Again",
    makeSureEmailSame:  "Please make sure that your email is the same for both fields.",
    makeSureValidEmailChange: "Please make sure the email you enter is a valid email address.",
    emailChangeSuccess: "Email Change Successful",
    emailUpdateFail:  "Email Update Failed.",
    emailAlreadyRegistered: "This email is already registered.",
    invalidPasswordEntry:  "Invalid Password Entry",
    passwordSameOld: "You cannot choose your new password to be your current one.",
    passwordUpdateFail:  "Password Update Failed.",
    makeSureCorrectCurrPassword:  "Please make sure you have entered the correct current password.",
    invalidUsernameEntry: "Invalid Username Entry",
    makeSureUsernameSame: "Please make sure that the username is the same for both fields.",
    userElevateSuccess:  "User Successfully Elevated to Admin.",
    promotedLogBackIn: "They will need to log out and log back in for this change to take effect.",
    userElevateFail: "User elevation failed",
    mustBeAdmin: "You must be an Admin to elevate users.",
    mustBeAuth: "You must be authenticated to elevate users.",
    userNotFound:  "There is no user with that username.",
    deactivateSuccess: "Deactivation Successful, You will now be logged out.",
    deactivateFail: "Deactivation Failed.",
    cameraRollPermissions: 'Sorry, we need camera roll permissions to allow you to select an image from your device!',
    profilePicUpdateSuccess: "Profile picture has been updated",
    profilePicUpdateFail: "Sorry something went wrong when updating your image, please try again",
    changeFullName: "Change Full Name",
    newName: 'New Name',
    update: 'Update',
    changeEmail: 'Change Email',
    newEmail: "New Email",
    confirmEmail: "Confirm Email",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: 'New Password',
    elevateUserToAdmin: "Elevate a User to Admin",
    usernameToElevate: "Username to Elevate",
    confirmUsername: "Confirm Username",
    elevate: "Elevate",
    banUserModal: "Ban a User",
    banUsername: "Username to Ban",
    ban: "Ban",
    userBanSuccess:  "User Successfully Banned.",
    bannedMessage: "This user will no longer have access to their account.",
    userBanFail: "User ban failed",
    deactivateAccount: "Deactivate Account",
    confirmDeactivation: 'Confirm Deactivation',
    pleaseConfirmDeactivation: 'Please confirm that you are deactivating your account.',
    profileInfo: 'Profile Information',
    updatePic: 'Update Picture',
    removePic: 'Remove Picture',
    deletePicConfirmation:  'Are you sure that you want to delete this profile picture?',
    userProfile: 'User Profile',
    userBlocked: 'This user has been successfully blocked',
    userUnBlocked: 'This user has been successfully unblocked',
    blockUser: 'Block User',
    unBlockUser: 'Unblock User',

    //Privacy Screen
    downloadData: "Download your Data",
    viewTerms: "View Terms of Service",
    viewPrivacy: "View Privacy Policy",

    //NewRecordingScreen
    maxLengthAlert: "Recording can be 3 minutes max",
    audioFilesPermission: "This permission is required in order to download audio files",
    downloadSuccess: "File has been successfully added to Downloads folder",
    downloadFail: "Something went wrong during download",
    audioPermissionPrompt: 'You must enable audio recording permissions in order to use this app.',
    maxLengthStatic: '3 Minutes Maximum',
    uploadExistingFile: 'Upload Existing File',

    //NewStoryScreen
    imageSelected: "Image has been selected",
    emptyTitle: "Please give your story a title!",
    emptyAuthor: "Please give the story an author!",
    maxStoredLengthAlert: 'Stories must be maximum 3 minutes in length',
    submissionUnderReview: "Your submission is under review!",
    newStorySubmissionTitle: "Submit Your New Story For Review!",
    isThisStorySave: 'Is this a Story for the Story Save \n Collection?',
    author: 'Author',
    no: 'No',
    title: 'Title',
    description: "Description",
    tags: 'Tags',
    processingImage: 'Processing Image',
    submissionInProgress: 'Submitting Your Story',
    uploadThumbnail: 'Upload Thumbnail Image',
    submit: 'Submit',
    next: 'Next',

    //NewComment
    somethingWentWrong: "Sorry something went wrong, please try again.",
    inputResponse: "Input your response",

    //ForgotPassword
    enterEmail: 'Please enter your email',

    //ResetPassword
    codeSentToEmailReset: 'A code was sent to your email. Please enter it below, then enter your new password',

};

// export const fr = {
//     //Translate to French
//      //Login Page
//      loginMessage: 'Login to the Storytellers App',
//      username: 'Username',
//      password: 'Password',
//      signIn: 'Sign In',
//      registerMessage: 'Register a New Account',
//      forgotPassword: 'Forgot Password',
//      dontWantAccount: "Don't want an account?",
//      loginAsGuest: 'Login as a Guest',
//      invalidLogin: "Invalid Login Information",
//      makeSureUserValid:  "Please make sure the username and password you enter is valid.",
//      missingLogin: "Missing Login Information",
//      makeSureInfoEntered: "Please make sure you have entered information in all fields before trying to login.",
     
//      //Registration Page
//      createYourAccountMessage: 'Créer votre compte de Conteurs',
//      fullName: "Nom et prénom",
//      email: 'Email',
//      confirmPassword: "Confirmez mot de passe",
//      register: "Register",
//      alreadyHaveAccount: 'Already have an account?',
//      login: 'Se connecter',
//      termsOfServiceMessage: 'By selecting Register, you agree to the',
//      termsOfService: "Conditions générales",
//      and: 'et',
//      privacyPolicy: 'la Politique d\'utilisation des données',
//      missingRegistrationInfo:  "Il y a l'information qui manques",
//      makeSureRegisterInfoEntered: "Please make sure you have entered information in all fields before trying to register.",
//      passwordMismatch: "Please make sure that your new password is the same for both fields.",
//      invalidEmail: "Invalid Email",
//      makeSureValidEmailEntered:  "Please make sure you have entered a valid email before trying to register.",
//      invalidRegistration: "Invalid Registration Information",
 
//      //Email Verification
//      incorrectEmailCode: "Incorrect code, please try again",
//      errorReachingServer: "Il y a un problem d'internet. Veuillez réessayer",
//      codeSentToEmail: 'Un code à été envoyé à votre email',
//      pleaseEnterCodeHere: 'Entrez le code ici pour vérifier votre email',
//      verificationCode: "Code de vérification",
//      confirm: 'Confirmer',
//      resendCode: "renvoyer code de vérification",
 
//      //HomeScreen
//      search: 'Rechercher',
//      helpCapitals: 'Aide',
//      helpHomeTitle: 'This is the Home Screen',
//      helpHomeStories: "All of the stories made by users will appear here. You can scroll through them, or click on any story to view its comments.",
//      helpHomeLikes: "If you want to \"like\" a story, tap the heart. If you want to comment on a story, tap the speech bubble.",
//      helpHomeRecording: 'Tap the blue microphone button to record your own story!',
 
//      //CardFooter
//      pleaseLoginToLike: "Veuillez-vous connecter pour aimer une histoire",
//      pleaseLoginToRecord: "Veuillez-vous connecter pour enrigestrer une histoire",
//      reply: "Repondre",
//      comment: 'Commentaire',
//      audio: 'Enregistrement', // Is this correct in the context?
//      deleteConfirmation: 'Êtes-vous sûr que vous voullez supprimer c\'ette histoire?',
//      cancel: 'Annuler',
//      yes: 'Oui',
 
//      //ResponseScreen
//      responses: 'Réponses',
 
//      //StorySaveScreen
//      helpStorySaveTitle: "This is the StorySave Collection Screen",
//      helpStorySaveStories: "All of the stories here are from the SC-Radio-CC StorySave collection. You can scroll through them, or click on any story to view its comments.",
//      storySaveCollection: "StorySave Collection",
 
//      //RadioPlayer
//      helpRadioTitle: 'Cela est l\'écran de SC-Radio-CC',
//      helpRadioMessage: 'Ici, vous pouvez écouter à la station SC-Radio-CC en direct',
//      scRadio: 'SC-Radio-CC',
 
//      //AdminPanel
//      helpAdminTitle: 'Cela est le panneau d\'administration',
//      helpAdminStories: 'Ici, vous pouvez approuver ou rejeter des histoires qui attendent d\'être approuver.',
//      helpAdminControls: 'Appuyer sur le bouton vert pour approuver une histoire, or appuyer sur le bouton rouge pour le rejeter',
//      adminPanel: 'Panneau d\'administration',
 
//      //DrawerContent
//      pleaseLoginToViewProfile: "Please login to view profile information",
//      guestUser: 'Guest User',
//      home: 'Acceuil',
//      profile: 'Profil',
//      privacy: 'Confidentialité',
//      signOut: 'Déconnecter',
 
//      //ProfileScreen
//      nameChangeSuccess: "Changement de nom réussi",
//      nameUpdateFail: "Changement de nom échouer",
//      pleaseTryAgain: "Veuillez réessayer",
//      makeSureEmailSame:  "Please make sure that your email is the same for both fields.",
//      makeSureValidEmailChange: "Please make sure the email you enter is a valid email address.",
//      emailChangeSuccess: "Changement de email réussi",
//      emailUpdateFail:  "Changement de email échouer",
//      emailAlreadyRegistered: "Cet email est déja enregister",
//      invalidPasswordEntry:  "Mot de passe invalide",
//      passwordSameOld: "You cannot choose your new password to be your current one.",
//      passwordUpdateFail:  "Password Update Failed.",
//      makeSureCorrectCurrPassword:  "Please make sure you have entered the correct current password.",
//      invalidUsernameEntry: "Invalid Username Entry",
//      makeSureUsernameSame: "Please make sure that the username is the same for both fields.",
//      userElevateSuccess:  "User Successfully Elevated to Admin.",
//      promotedLogBackIn: "They will need to log out and log back in for this change to take effect.",
//      userElevateFail: "User elevation failed",
//      mustBeAdmin: "You must be an Admin to elevate users.",
//      mustBeAuth: "You must be authenticated to elevate users.",
//      userNotFound:  "There is no user with that username.",
//      deactivateSuccess: "Deactivation Successful, You will now be logged out.",
//      deactivateFail: "Deactivation Failed.",
//      cameraRollPermissions: 'Sorry, we need camera roll permissions to allow you to select an image from your device!',
//      profilePicUpdateSuccess: "Profile picture has been updated",
//      profilePicUpdateFail: "Sorry something went wrong when updating your image, please try again",
//      changeFullName: "Changer nom et prénom",
//      newName: 'Nouveau nom',
//      update: 'Mise à jour',
//      changeEmail: 'Changer email',
//      newEmail: "Nouveau email",
//      confirmEmail: "Confirmer email",
//      changePassword: "Changer mot de passe",
//      currentPassword: "Mot de passe actuel",
//      newPassword: 'Nouveau mot de passe',
//      elevateUserToAdmin: "Elevate a User to Admin",
//      usernameToElevate: "Username to Elevate",
//      confirmUsername: "Confirm Username",
//      elevate: "Elevate",
//      banUserModal: "Ban a User",
//      banUsername: "Username to Ban",
//      ban: "Ban",
//      userBanSuccess:  "User Successfully Banned.",
//      bannedMessage: "This user will no longer have access to their account.",
//      userBanFail: "User ban failed",
//      deactivateAccount: "Deactivate Account",
//      confirmDeactivation: 'Confirm Deactivation',
//      pleaseConfirmDeactivation: 'Please confirm that you are deactivating your account.',
//      profileInfo: 'Information de profil',
//      updatePic: 'Update Picture',
//      removePic: 'Remove Picture',
//      deletePicConfirmation:  'Are you sure that you want to delete this profile picture?',
//      userProfile: 'User Profile',
//      userBlocked: 'This user has been successfully blocked',
//      userUnBlocked: 'This user has been successfully unblocked',
//      blockUser: 'Block User',
//      unBlockUser: 'Unblock User',

//      //Privacy Screen
//      downloadData: "Télecharger votre information",
//      viewTerms: "Lire les conditions générales",
//      viewPrivacy: "Lire la Politique d\'utilisation des données",
 
//      //NewRecordingScreen
//      maxLengthAlert: "Enrigestrement peut être jusqu'à trois minute de long",
//      audioFilesPermission: "This permission is required in order to download audio files",
//      downloadSuccess: "Fichier à été téléchargé avec succès",
//      downloadFail: "Something went wrong during download",
//      audioPermissionPrompt: 'You must enable audio recording permissions in order to use this app.',
//      maxLengthStatic: '3 Minutes Maximum',
//      uploadExistingFile: 'Upload Existing File',
 
//      //NewStoryScreen
//      imageSelected: "Une image a été choisi",
//      emptyTitle: "Please give your story a title!",
//      emptyAuthor: "Please give the story an author!",
//      maxStoredLengthAlert: 'Stories must be maximum 3 minutes in length',
//      submissionUnderReview: "Your submission is under review!",
//      newStorySubmissionTitle: "Submit Your New Story For Review!",
//      isThisStorySave: 'Is this a Story for the Story Save \n Collection?',
//      author: 'Auteur',
//      no: 'Non',
//      title: 'Titre',
//      description: "Description",
//      tags: 'Mots clés',
//      processingImage: 'Processing Image',
//      submissionInProgress: 'Nous envoyons votre histoire',
//      uploadThumbnail: 'Upload Thumbnail Image',
//      submit: 'Soumettre',
//      next: 'Suivant',
 
//      //NewComment
//      somethingWentWrong: "Sorry something went wrong, please try again.",
//      inputResponse: "Input your response",
 
//      //ForgotPassword
//      enterEmail: 'Veuillez entrer votre addresse courriel',
 
//      //ResetPassword
//      codeSentToEmailReset: 'A code was sent to your email. Please enter it below, then enter your new password',
 
// };